import React from 'react'
import { useNavigate } from 'react-router-dom'
import '../css/reservationCheck.css'

const ReservationCheck = () => {

  const navigate = useNavigate();

  return (
    <div className='reCheck-container'>
      <div>
        <h2>진료예약조회</h2>
      </div>
      <div>
        <ul>
          <li>2024.08</li>
        </ul>
      </div>
      <div className='day-container'>
        <table>
          <thead>
            <tr>
              <td>일</td>
              <td>월</td>
              <td>화</td>
              <td>수</td>
              <td>목</td>
              <td>금</td>
              <td>토</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <div>28</div>
              </td>
              <td>
                <div>29</div>
              </td>
              <td>
                <div>30</div>
              </td>
              <td>
                <div>31</div>
              </td>
              <td>
                <div>1</div>
              </td>
              <td>
                <div>2</div>
              </td>
              <td>
                <div>3</div>
              </td>
            </tr>
            <tr>
              <td>
                <div>4</div>
              </td>
              <td>
                <div>5</div>
              </td>
              <td>
                <div>6</div>
              </td>
              <td>
                <div>7</div>
              </td>
              <td>
                <div>8</div>
              </td>
              <td>
                <div>9</div>
              </td>
              <td>
                <div>10</div>
              </td>
            </tr>
            <tr>
              <td>
                <div>11</div>
              </td>
              <td>
                <div>12</div>
              </td>
              <td>
                <div>13</div>
              </td>
              <td>
                <div>14</div>
              </td>
              <td>
                <div>15</div>
              </td>
              <td>
                <div>16</div>
              </td>
              <td>
                <div>17</div>
              </td>
            </tr>
            <tr>
              <td>
                <div>18</div>
              </td>
              <td>
                <div>19</div>
              </td>
              <td>
                <div>20</div>
              </td>
              <td>
                <div>21</div>
              </td>
              <td>
                <div>22</div>
              </td>
              <td>
                <div>23</div>
              </td>
              <td>
                <div>24</div>
              </td>
            </tr>
            <tr>
              <td>
                <div>25</div>
              </td>
              <td>
                <div>26</div>
              </td>
              <td>
                <div>27</div>
              </td>
              <td>
                <div>28</div>
              </td>
              <td>
                <div>29</div>
              </td>
              <td>
                <div>30</div>
              </td>
              <td>
                <div>31</div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default ReservationCheck